name: ModerationUtils
main: com.mnewt00.moderationutils.ModerationUtils
version: @version@

author: mnewt00
description: ModerationUtils is a small set of tools to make moderating easier.

depend: [PremiumVanish, LunarClient-API]
softdepend: [PlaceholderAPI]

api-version: 1.18